### ISSUE TITLE
"deleteme" Files

### ISSUE THREAD

**Issue by hackinghacker1** [Abnumality/abnumality-gaming#1]
In all the locations where there is supposed to be games is a "deleteme" file

**Comment by Abnumality** [comment]
> In all the locations where there is supposed to be games is a "deleteme" file

"deleteme" So what do you think you should do based on the name of the file?

**Comment by hackinghacker1** [comment]
> > In all the locations where there is supposed to be games is a "deleteme" file
> 
> "deleteme" So what do you think you should do based on the name of the file?

Yeah, but where are the game files?

**Comment by Abnumality** [comment]
> Yeah, but where are the game files?

put them in there yourself, it's not my job to provide those for you
